### ISSUE TITLE
multicamera

### ISSUE THREAD

**Issue by natxopedreira** [brinoausrino/ofxGphoto#2]
Hello

I have a project im running on windows but want to move to linux as my preference, thanks for the addon.

Did you tried more than one camera? I get an error
`[ error ] ofxGphoto::setup: Camera initialisation error - -53   Could not claim the USB device`

The lib recognize the two cameras
`[notice ] ofxGphoto::listDevices: Number of cameras : 2`

**Comment by natxopedreira** [comment]
Solved, seems you need to set port data, set capabilities, etc before init camera:

[https://gist.github.com/natxopedreira/c647b334acf6356ad4ebef6691140867](https://gist.github.com/natxopedreira/c647b334acf6356ad4ebef6691140867)

Now i can use 2 cameras, do you want a pr?

Thanks for the addon!!

**Comment by brinoausrino** [comment]
Nice, you solved it! I didn't have the capabilities since I only had one camera here.
Yes, please send a pr and thank you.

**Comment by natxopedreira** [comment]
pr done

maybe also nice put a comment in the readme that:
+ can be used without sdcard in the camera
+ is not affected by the 15 min max liveview as in the cannon sdk, so not need to reset
+ in the case of using a sdcard camera needs to be unmounted...

PD works very nice, i have been testing it to replace my app with canon sdk and is really great, thanks!
